version: "3.1"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    restart: always
    ports:
      - 27345:27017
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: GocCt7YNR8GTj2Xh
    networks:
      - default